# Generated by Django 5.2.17 on 2026-09-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackthon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
