# Generated by Django 5.2.17 on 2026-09-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackthon', '0002_alter_complaint_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='gps_image',
            field=models.ImageField(blank=True, null=True, upload_to='complaints/gps/'),
        ),
    ]
