# Generated by Django 5.2.17 on 2026-09-05 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackthon', '0003_complaint_gps_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='gps_image',
        ),
    ]
